version: '2'
services:
  app:
    restart: always
    build:
      context: .
      args:
        - SSLDOMAIN=${SSLDOMAIN}
    command: bash -c "redis-server --daemonize yes && service cron start && rails db:migrate && foreman start"
    volumes:
        - ${VOLUMEMOUNTPATH}/cert:/etc/letsencrypt/live/${SSLDOMAIN}
        - ${VOLUMEMOUNTPATH}/settings.yml:/var/www/ldap-oauth2-provider/config/ldap_config.yml
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
